Human v. Human Tic Tac Toe
jchung722/tic_tac_toe_elixir pull request #1
Opened 2019-04-16 18:52 UTC by jchung722

Here's what I have so far with human vs. human tic tac toe. Note that I'm skipping one of the tests for the Game.play method;  Lucas and I were working on properly testing it, but we couldn't figure it out. We were thinking that it might have to be refactored to be testable. 

Looking forward to your feedback!

2019-04-16 19:09 UTC, cmvandrevala commented on .gitignore
> +.elixir_ls
What is the community standard for checking in the `.elixir_ls` file? I know some people like to check in config files and others do not.

Regardless, it is good that you added the beam files to the gitingore

2019-04-16 19:09 UTC, cmvandrevala commented on lib/board.ex
> +  defstruct data: ["1", "2", "3", "4", "5", "6", "7", "8", "9"]
Can you think of a better name than "data"?

2019-04-16 19:09 UTC, cmvandrevala commented on lib/board.ex
> +  def build(board_data) do
This function can probably be refactored into something much simpler.

2019-04-16 19:09 UTC, cmvandrevala commented on lib/status.ex
> +  # checks if game has a tie
You can remove this comment

2019-04-16 19:09 UTC, cmvandrevala commented on lib/status.ex
> +  # checks if a player won the game
You can remove this comment

2019-04-16 19:09 UTC, cmvandrevala commented on test/board_test.exs
> +      assert board_data.data == context[:board]
I would get rid of the setup block and just write out the assertion in each test. Yes, it is a bit longer, but it makes each test more self-contained.

2019-04-16 19:09 UTC, cmvandrevala commented on test/board_test.exs
> +      assert board_data.data == context[:board]
https://stackoverflow.com/questions/6453235/what-does-damp-not-dry-mean-when-talking-about-unit-tests

2019-04-16 19:09 UTC, cmvandrevala commented on test/game_test.exs
> +    setup do
I would get rid of this setup block as well

2019-04-16 19:09 UTC, cmvandrevala commented on test/game_test.exs
> +    @tag :skip
It is totally fine to have a skip tag while you are getting feedback, but be sure to remove it or delete the test before submitting the final PR

2019-04-16 19:09 UTC, cmvandrevala commented on test/input_test.exs
> +  doctest Input
Are you using doctest anywhere? Can you remove that in your tests?

2019-04-16 19:09 UTC, cmvandrevala commented on test/input_test.exs
> +  describe "when input is valid" do
Do you have test cases for when the input is not valid?

2019-04-16 19:09 UTC, cmvandrevala commented on test/status_test.exs
> +    setup do
This might be a case where a setup block is ok.

2019-04-16 19:09 UTC, cmvandrevala commented on test/status_test.exs
> +  describe "end of game" do
Nice tests. Great job

2019-04-16 19:09 UTC, cmvandrevala commented on test/tic_tac_toe_elixir_test.exs
>  defmodule TicTacToeElixirTest do
If this module is not being used, why not delete it?

2019-04-16 19:09 UTC, cmvandrevala commented on test/player_test.exs
> +  end
What happens if a value is not "X" or "O"?

2019-04-16 19:09 UTC, cmvandrevala commented on test/game_test.exs
> +      assert capture_io(fn ->
I like how you are attempting to test around IO using the `capture_io` function. We will talk about more advanced testing strategies over the next few months

2019-04-16 19:09 UTC, cmvandrevala commented on test/board_test.exs
> +      assert Board.build(board_data.data) == "| 1 | 2 | 3 |\n| 4 | 5 | 6 |\n| 7 | 8 | 9 |"
Does the board have horizontal lines? Doesn't a tic-tac-toe board look like an octothorp - #?

2019-04-16 20:30 UTC, jchung722 commented on test/board_test.exs
> +      assert Board.build(board_data.data) == "| 1 | 2 | 3 |\n| 4 | 5 | 6 |\n| 7 | 8 | 9 |"
The board didn't have horizontal lines before; I changed it now so it looks more like an octothorp!

2019-04-17 14:25 UTC, jchung722 commented on test/input_test.exs
> +  describe "when input is valid" do
not yet! I might have to work on input validation for the next sprint

2019-04-17 14:28 UTC, jchung722 commented on test/input_test.exs
> +  describe "when input is valid" do
Ooh actually I will test for when input is valid for this method, and work out the rest of this module for the next sprint!

2019-04-17 16:54 UTC, jchung722 commented on .gitignore
> +.elixir_ls
there seems to be a mix of people who track/don't track `.elixir_ls` too;  I  just put it in my gitignore because it was cluttering my stage

2019-04-17 17:43 UTC, nc-nystromb commented on .gitignore
> +.elixir_ls
FWIW, it appears that the suggested `.gitignore` by github adds this file

https://github.com/github/gitignore/blob/master/Elixir.gitignore

2019-04-17 20:07 UTC, cmvandrevala requested changes

2019-04-17 20:07 UTC, cmvandrevala commented on lib/tic_tac_toe_elixir.ex
> +    #Initializes empty board and starts with player X
Remove this comment

2019-04-17 20:07 UTC, cmvandrevala commented on lib/status.ex
> +      Enum.at(board, 0) == Enum.at(board, 3) && Enum.at(board, 3) == Enum.at(board, 6) ->
There is some duplication in these `cond` statements. Maybe refactor to eliminate some of it?

2019-04-17 20:07 UTC, cmvandrevala commented on lib/status.ex
> +  # helper function for win? - checks if rows have win condition
You can delete this comment

2019-04-17 20:07 UTC, cmvandrevala commented on lib/status.ex
> +  # check if game is over
You can delete this comment

2019-04-17 20:07 UTC, cmvandrevala commented on lib/board.ex
> +  def build([]), do: ""
I would consider changing the name of this function. Maybe `formatted_board` or something?

2019-04-17 20:07 UTC, cmvandrevala commented on lib/board.ex
> +  def build([]), do: ""
I really like this refactoring. Your `build` method is pretty neato tostido

2019-04-18 16:53 UTC, cmvandrevala approved these changes

2019-04-18 17:11 UTC, merged