Player
jchung722/tic_tac_toe_elixir pull request #5
Opened 2019-04-30 14:59 UTC by jchung722

1. My validation method for a symbol input was my attempt at polymorphism - does that make sense here?
2. Note: Currently the program doesn't work properly if symbol is a number
3. Would it make sense for me to make a Game struct that holds board & players?

2019-04-30 20:16 UTC, nc-nystromb commented on lib/game.ex
> +    case Input.validate(input, board, current_player, next_player) do
This function seems to be needing to know so much more about everything about the game. Perhaps this method could live somewhere other than `Input`? Just something to think about.

2019-05-01 16:08 UTC, bgerstle reviewed
Left a few comments, but my two main talking points are:

`Board.update` argument validation vs. `Game`/`Input` validating spots before calling `update`. For me, it comes down to the question of why it should be allowed to call `Board.update` with "invalid" arguments at any point in time. My argument is that it should never be allowed, and the `Board` API should be defensive by explicitly raising errors when given invalid inputs. Other classes (like `Game` or `Input`) could catch them and inform the user before trying again.

There appear to be several uses of `cond` where an `if` statement would suffice. Is there something about Elixir that explains why `cond` is preferred?

2019-05-01 16:08 UTC, bgerstle commented on lib/board.ex
> +  def update(move_as_index, board, player) do
The `Input` validating functions you wrote could apply here as well. Any reason not to have the `Board` be the single source of truth for what can/can't be done with a board?

2019-05-01 16:08 UTC, bgerstle commented on lib/input.ex
> +  def validate(symbol) do
Is having multiple overloads for the `validate` functions what you were referring to as polymorphism? I'm not much of an elixir programmer, but I would have expected different modules implementing their own `validate` function as opposed to one module with different patterns.

For example, you could have a `MoveValidator`and a `PlayerTokenValidator`.

2019-05-01 16:08 UTC, bgerstle commented on lib/input.ex
> +      move_board_index < max_range && move_board_index >= 0 ->
Seems like an `if`/`else` statement would be more appropriate here.

2019-05-01 16:08 UTC, bgerstle commented on lib/status.ex
>        win?(board) ->
Again, seems weird to be to have a catch-all `true` condition instead of an if/else-if/else, but maybe that's idiomatic in Elixir.

2019-05-01 16:08 UTC, bgerstle commented on test/board_test.exs
> +      assert Board.format(board) == " 1 | \e[32mX\e[0m | 3 \n---+---+---\n 4 | \e[32mO\e[0m | 6 \n---+---+---\n 7 | 8 | 9 "
Seeing a lot of copy/pasting for the row/column separators, perhaps worth replacing with a constant?

2019-05-01 16:08 UTC, bgerstle commented on lib/player.ex
> +        IO.puts("Invalid symbol. Must be single alphanumeric character."); :timer.sleep(1000)
Why is there a sleep here?

2019-05-01 16:19 UTC, nc-nystromb commented on lib/input.ex
> +  def validate(symbol) do
Agreed with this. My brain kind of breaks when I think of polymorphism in a functional language. Is true polymorphism a thing in functional languages? I'm not sure.

I think she is referring to "pattern matching" instead.

2019-05-01 16:39 UTC, jchung722 commented on lib/input.ex
> +  def validate(symbol) do
Oops. Yes I think you're right and I'm working more on pattern matching than polymorphism here 👀. Will move them to separate modules!

2019-05-01 16:47 UTC, jchung722 commented on lib/player.ex
> +        IO.puts("Invalid symbol. Must be single alphanumeric character."); :timer.sleep(1000)
Good point; it doesn't need to be here. Will remove!

2019-05-01 16:54 UTC, jchung722 commented on lib/status.ex
>        win?(board) ->
Yes, the true condition acts as the "else". From what I've heard, it seems like cond/do is preferred because it handles multiple conditions whereas if/else can only handle one, so I think pattern matching is preferred over if/else.

I think this is serving a good reminder for me to think of refactoring to pattern matching though.

2019-05-02 17:16 UTC, bgerstle requested changes
Two main items to address:

- Using `Input` in the `Board` module. The idea here is to keep "core" modules of your app free from having to deal with stuff from the outside world.
- Missing test case for `tie?` and possible problems with the `Status` module API design

2019-05-02 17:16 UTC, bgerstle commented on lib/board.ex
> +    case Input.move_validator(move, board) do
I wouldn't mix `Board` and `Input`. IMO `Input` is about handling raw data from the outside world, and `Board` should only have to deal with inputs that are defined by its interface, i.e. a `move` should already be a board index.

2019-05-02 17:16 UTC, bgerstle commented on test/player_test.exs
> +      player_symbol = "X"
you've got alpha, but what about numeric?

2019-05-02 17:16 UTC, bgerstle commented on test/player_test.exs
> +      player_symbol = "X"
Also, do numeric tokens make sense? Consider this board:

```
1 | 2 | 3
X | 5 | X
7 | 8 | 1
```

Is spot 1 taken? 😈 

This is more of a UX decision than a technical one, but it's good to think about edge cases and be a little skeptical of your requirements.

2019-05-02 17:16 UTC, bgerstle commented on lib/status.ex
> +  def tie?([ %Player{} | tail]), do: tie?(tail)
That's some very clever pattern matching 🤓

2019-05-02 17:16 UTC, bgerstle commented on test/status_test.exs
> -      assert Status.tie?(board, playerX, playerO) == true
You need to add a case for a full board where there _is_ a winner. I suspect your `tie?` function will return a false positive (i.e. it says the game is a tie even though a player won). If that's the case, we can talk about the `Status` module's API design and how to avoid these kinds of issues.

2019-05-02 17:18 UTC, bgerstle commented on test/status_test.exs
> +      playerX = %Player{name: "playerX", symbol: "X"}
Another point about the `Status` module API design: having separate `tie?` `win` and `result` methods is forcing you to check their output for the same inputs. There are ways you can simplify the `Status` API and remove the need for these kinds of tests.

2019-05-02 17:20 UTC, bgerstle commented on test/status_test.exs
> +      playerX = %Player{name: "playerX", symbol: "X"}
Specifically: a board should only have one result. Having multiple functions to obtain a result forces you to make sure they're all consistent (i.e. you can never have a board where `result`, `win?`, and `tie?` contradict each other).

2019-05-02 19:20 UTC, jchung722 commented on test/player_test.exs
> +      player_symbol = "X"
Added the test for numeric!

Ah yes, the numeric tokens was a specific request from Cyrus so I'd have to change my board data structure 😦. I did add a feature that makes moves made by players green though, so that should help distinguish which spots are taken when using numeric tokens.

2019-05-02 19:43 UTC, jchung722 commented on test/status_test.exs
> +      playerX = %Player{name: "playerX", symbol: "X"}
Thanks for the insight, Brian! Then do you think it would make better sense to make `win?` and `tie?` private methods with `result` as the only accessible API?

2019-05-03 21:01 UTC, bgerstle approved these changes
Looking good! 👍

2019-05-03 21:13 UTC, merged