Simple Computer vs. Human
jchung722/tic_tac_toe_elixir pull request #6
Opened 2019-05-06 16:00 UTC by jchung722

2019-05-06 16:33 UTC, cmvandrevala requested changes

2019-05-06 16:33 UTC, cmvandrevala commented on lib/computer.ex
> +    Board.available_spots(board) |>
```
board
|> Board.available_spots
|> Enum.random
```

2019-05-06 16:33 UTC, cmvandrevala commented on test/player_test.exs
> +  end
According to this, I can insert any sort of string for a player type. `%Player{type: "purple unicorn"}` is a valid option. Is there a way that you can restrict the options to human or computer? Maybe have `%HumanPlayer` and `%ComputerPlayer` structs? Or maybe leverage functions to generate the structs (e.g. `def human_player() do: %Player{type: "human"}`?

2019-05-06 16:33 UTC, cmvandrevala commented on test/player_test.exs
> +  end
This kind of ties into what I was saying above. Instead of creating a player and validating the type, why not just restrict the types of players that can be created in the first place?

2019-05-06 16:33 UTC, cmvandrevala commented on test/computer_test.exs
> +  test "a computer will make a random move from available spots" do
You can test the random function more thoroughly with the following steps:

1. Read up on what a seed is when generating random numbers (if you don't already know)
2. Change the function signature of the random move to: `def random_move(board, seed) do`
3. Inject specific seeds into the `random_move` function and unit test their outputs.
4. Inject a default random seed into the game when playing on the command line

2019-05-06 16:33 UTC, cmvandrevala commented on test/board_test.exs
> +      assert Board.available_spots(board_spots) == ["1", "2", "3", "4", "5", "6", "7", "8", "9"]
No need to change this, but it is weird to me that the integers marking the cells are stored as strings. It is almost as if your board has knowledge of your I/O (i.e. printing the cells to the console). If you have extra time, I might refactor that to regular old integers and have the printer convert from integer to string when needed.

2019-05-06 16:33 UTC, cmvandrevala commented on lib/player.ex
> +    %Player{name: player_name, symbol: player_symbol, type: player_type}
There is a lot going on in the function, and it does not look well tested. Maybe refactor this function?

2019-05-06 16:33 UTC, cmvandrevala commented on lib/player.ex
> +        console_input_type(player)
There is a lot going on in this function and it does not look well tested. One strategy you might use is to separate the IO (e.g. `Input.gets`) from the business logic (e.g. `case type_validator(...)` into two separate functions. Then, you can easily test the business logic.

2019-05-07 20:45 UTC, jchung722 commented on test/board_test.exs
> +      assert Board.available_spots(board_spots) == ["1", "2", "3", "4", "5", "6", "7", "8", "9"]
Will do for next PR! :)

2019-05-07 21:05 UTC, cmvandrevala requested changes

2019-05-07 21:05 UTC, cmvandrevala commented on lib/computer.ex
> +    _ = seed
What does `_ = seed` do?

2019-05-07 21:05 UTC, cmvandrevala commented on lib/game.ex
> +    move = Computer.random_move(board) |> Input.to_board_index()
```
board
|> Computer.random_move
|> Input.to_board_index
```

2019-05-07 21:05 UTC, cmvandrevala commented on lib/player.ex
> +  def computer_player(), do: %Player{type: "COMPUTER"}
Why have the `create("WHATEVER")` functions and the `human_player`/`computer_player` functions together? Are both used? I think you can use one or the other.

2019-05-07 21:05 UTC, cmvandrevala commented on lib/player.ex
> +  def type_validator(type) do
Do you still need the validator here if you have the functions to create human and computer players?

2019-05-07 21:05 UTC, cmvandrevala commented on test/computer_test.exs
> +    assert Computer.random_move(board, seed) == "4"
Nice 👍

2019-05-07 21:10 UTC, jchung722 commented on lib/computer.ex
> +    _ = seed
I think that's what I need to do to set the random seed; it wouldn't let me just put `seed` alone :/

2019-05-07 21:14 UTC, jchung722 commented on lib/computer.ex
> +    _ = seed
...but I just made it expressive by making it `_set_random_seed = seed`...:D

2019-05-07 21:49 UTC, jchung722 commented on lib/player.ex
> +  def computer_player(), do: %Player{type: "COMPUTER"}
I refactored to just use `create("TYPE")`, but I'm unsure how to test this without mocking input

2019-05-08 18:42 UTC, cmvandrevala approved these changes

2019-05-08 18:56 UTC, merged